image: node:16

stages:
    - build


build:
    stage: build
    before_script:
        - curl -f https://get.pnpm.io/v6.7.js | node - add --global pnpm@6
        - pnpm config set store-dir .pnpm-store
    script:
        - (echo "$BOT_ENV" | base64 -d) > .env
        - pnpm install # install dependencies
        - pnpm task # run task
    cache:
        key: "$CI_COMMIT_REF_SLUG"
        paths:
        - .pnpm-store
